trainingInput:
    scaleTier: BASIC_GPU
    hyperparameters:
      algorithm: GRID_SEARCH
      goal: MAXIMIZE
      maxTrials: 1
      maxParallelTrials: 1
      hyperparameterMetricTag: val_accuracy
      params:
      - parameterName: epochs
        type: DISCRETE
        discreteValues:
        - 100