kind: Deployment
apiVersion: apps/v1
metadata:
  name: audiolib-docs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiolib-docs
  template:
    metadata:
      labels:
        app: audiolib-docs
    spec:
      containers:
      - name: audiolib-docs-container
        image: gcr.io/pypi-282816/audiolib-docs
        ports:
        - containerPort: 8080
          name: http
---
kind: Service
apiVersion: v1
metadata:
  name: audiolib-docs-service
spec:
  selector:
    app: audiolib-docs
  ports:
  - protocol: TCP
    targetPort: 8080
    port: 80
    name: http
  type: LoadBalancer